services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mymariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - inception
    env_file:
      - .env
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mysql
      o: bind
networks:
  inception:
    driver: bridge

